### ISSUE TITLE
Error Validation of TestSummary 

### ISSUE THREAD

**Issue by gianghn** [Codeception/detox-helper#3]
When run codeception with detox-helper 

There was exception raised because beforeEach TestSummary does not include status attribute.

I have to fix at line 166 of detox.js file as following: 

```
  async _test(test) {
    await detox.beforeEach({
      title: test.title,
      fullName: test.fullTitle(),
      status: 'running',
    });
  }
```

**Comment by gianghn** [comment]
Here is the log:

```
(node:51566) UnhandledPromiseRejectionWarning: Error: DetoxRuntimeError: Invalid test summary status was passed to detox.beforeEach(testSummary). Valid values are: "running", "passed", "failed"

HINT: It seems like you've hit a Detox integration issue with a test runner. You are encouraged to report it in Detox issues on GitHub.

testSummary was: {
  "title": "I should see slider",
  "fullName": "FirstSlider: I should see slider"
}
    at Detox._validateTestSummary (/usr/local/lib/node_modules/@codeceptjs/detox-helper/node_modules/detox/src/Detox.js:145:15)
    at Detox.beforeEach (/usr/local/lib/node_modules/@codeceptjs/detox-helper/node_modules/detox/src/Detox.js:110:10)
    at DetoxExportWrapper.(anonymous function).args [as beforeEach] (/usr/local/lib/node_modules/@codeceptjs/detox-helper/node_modules/detox/src/DetoxExportWrapper.js:46:34)
    at Detox._test (/usr/local/lib/node_modules/@codeceptjs/detox-helper/Detox.js:167:17)
    at Object.keys.forEach (/usr/local/lib/node_modules/codeceptjs/lib/listener/helpers.js:16:25)
    at Array.forEach (<anonymous>)
    at runHelpersHook (/usr/local/lib/node_modules/codeceptjs/lib/listener/helpers.js:15:26)
    at EventEmitter.event.dispatcher.on (/usr/local/lib/node_modules/codeceptjs/lib/listener/helpers.js:39:5)
    at EventEmitter.emit (events.js:203:15)
    at Object.emit (/usr/local/lib/node_modules/codeceptjs/lib/event.js:51:28)
    at Context.test.fn (/usr/local/lib/node_modules/codeceptjs/lib/scenario.js:77:13)
    at callFnAsync (/usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:415:21)
    at Test.Runnable.run (/usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:357:7)
    at Runner.runTest (/usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:535:10)
    at /usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:653:12
    at next (/usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:447:14)
(node:51566) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:51566) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DavertMik** [comment]
> I have to fix at line 166 of detox.js file as following:

Hey, could you send a pull request?
